//MODULE CALENDAR
export const SET_PERIOD = "SET_PERIOD";
export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
export const SET_OFFSET_MONTH = "SET_OFFSET_MONTH";

//MODULE CLINICA
export const SET_CLINICA = "SET_CLINICA";
export const SET_HORARIOS = "SET_HORARIO";

//MODULE AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
