// GERAL
export const END_LOADING = "END_LOADING";

//MODULE CALENDAR
export const SET_NOW = "SET_NOW";
export const SET_PERIOD = "SET_PERIOD";
export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
export const SET_OFFSET_MONTH = "SET_OFFSET_MONTH";
export const SET_OFFSET_MONTH_PICKER = "SET_OFFSET_MONTH_PICKER";

//MODULE CLINICA
export const SET_CLINICA = "SET_CLINICA";
export const SET_HORARIOS = "SET_HORARIO";
export const RESET_STATE = "RESET_STATE";
export const SET_CONSULTAS = "SET_CONSULTAS";

//MODULE AUTH
export const SET_AUTH_STATE = "SET_AUTH_STATE";
export const RESET_AUTH_STATE = "RESET_AUTH_STATE";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

// MODULE CLINICS
export const SET_CLINICS = "SET_CLINICS";
export const RESET_CLINICS_STATE = "RESET_CLINICS_STATE";

// MODULE PROFESSIONALS
export const SET_PROFESSIONALS = "SET_PROFESSIONALS";
export const RESET_PROFESSIONALS_STATE = "RESET_PROFESSIONALS_STATE";

// MODULE SCHEDULES
export const SET_SCHEDULES = "SET_SCHEDULES";
export const RESET_SCHEDULES_STATE = "RESET_SCHEDULES_STATE";
